version: "3.9"
services:
  app:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: muellmer:latest
    environment:
      NODE_ENV: production
      PORT: 3001
    env_file:
      - .env
    ports:
      - "${PORT:-3001}:3001"
    restart: unless-stopped
